# Generated by Django 5.2.7 on 2026-04-04 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Suez', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Egypt', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(default='Ali', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default='Amr', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1012458978, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='5 street', max_length=30),
            preserve_default=False,
        ),
    ]
