# Generated by Django 5.2.7 on 2026-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+20', max_length=5),
            preserve_default=False,
        ),
    ]
