# Generated by Django 5.2.7 on 2026-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='mod', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='mod', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+20', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mod@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(default='mod', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default='mod', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456789', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='01000000000', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='mod', max_length=30),
        ),
    ]
