# Generated by Django 5.2.7 on 2026-04-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0003_alter_tasks_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('list_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'to_do_list',
                'managed': True,
                'unique_together': {('user', 'list_name')},
            },
        ),
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('list_name', models.ForeignKey(db_column='list_name', on_delete=django.db.models.deletion.CASCADE, to='TO_DO_List.todolist')),
            ],
            options={
                'db_table': 'to_do_items',
                'managed': True,
                'unique_together': {('list_name', 'item_name')},
            },
        ),
    ]
