# Generated by Django 5.2.7 on 2026-04-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_List', '0001_initial'),
        ('Tasks', '0003_alter_tasks_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='status',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks'),
        ),
    ]
