# Generated by Django 5.2.13 on 2026-04-25 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_List', '0001_initial'),
        ('Tasks', '0003_alter_tasks_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='list_name',
            field=models.ForeignKey(db_column='list_name', on_delete=django.db.models.deletion.CASCADE, to='TO_DO_List.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks'),
        ),
    ]
