# Generated by Django 5.2.13 on 2026-06-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_List', '0003_alter_todoitems_list_name_alter_todolist_task'),
        ('Tasks', '0003_alter_tasks_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks'),
        ),
    ]
