# Generated by Django 5.2.7 on 2026-03-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('booking_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('number_of_persons', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=40, null=True)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks')),
            ],
            options={
                'db_table': 'hotels',
                'managed': True,
            },
        ),
    ]
