# Generated by Django 5.2.13 on 2026-04-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
        ('Tasks', '0003_alter_tasks_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks'),
        ),
    ]
