# Generated by Django 5.2.7 on 2026-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
