# Generated by Django 5.2.7 on 2026-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chats_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=5, null=True),
        ),
    ]
