# Generated by Django 5.2.7 on 2026-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
