# Generated by Django 5.2.7 on 2026-03-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveling',
            fields=[
                ('ticket_num', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_passengers', models.IntegerField(blank=True, null=True)),
                ('moving_method', models.CharField(blank=True, max_length=15, null=True)),
                ('moving_service_provider', models.CharField(blank=True, max_length=40, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks')),
            ],
            options={
                'db_table': 'traveling',
                'managed': True,
            },
        ),
    ]
