# Generated by Django 5.2.13 on 2026-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveling',
            name='return_date',
        ),
        migrations.AddField(
            model_name='traveling',
            name='departure_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveling',
            name='return_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveling',
            name='departure_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveling',
            name='ticket_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
