# Generated by Django 5.2.13 on 2026-04-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_chat'),
        ('flights', '0002_remove_traveling_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveling',
            name='task',
            field=models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks'),
        ),
    ]
