# Generated by Django 5.2.7 on 2026-03-15 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('pk', models.CompositePrimaryKey('task_id', 'to_email', blank=True, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks')),
            ],
            options={
                'db_table': 'email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('receiver_email', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
                'unique_together': {('nickname', 'contact_id')},
            },
        ),
    ]
