# Generated by Django 5.2.7 on 2026-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_emails', '0003_alter_email_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
