# Generated by Django 5.2.13 on 2026-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_emails', '0004_alter_tokens_expiry_alter_tokens_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
