# Generated by Django 5.2.7 on 2026-03-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('pk', models.CompositePrimaryKey('task_id', 'title', blank=True, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Tasks.tasks')),
            ],
            options={
                'db_table': 'reminder',
                'managed': True,
            },
        ),
    ]
