# Generated by Django 5.2.13 on 2026-04-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='booking_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='offer_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
