# Generated by Django 5.2.13 on 2026-04-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_tasks_booking_data_tasks_offer_data'),
        ('chat', '0005_alter_chats_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chats'),
        ),
    ]
